spring.application.name=central_data_hub
spring.mongodb.uri=mongodb+srv://db_user:08213edd@testdatabase.qrqnw1o.mongodb.net/?retryWrites=true&w=majority&appName=TestDatabase
spring.mongodb.database=Central_Data_Hub_Concept

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.context=DEBUG

management.endpoints.web.exposure.include=health,mappings
management.endpoint.health.show-details=always


